version: "3.8"

services:
  date-annotator:
    image: nlpsandbox/date-annotator-example:0.3.2
    build:
      context: server
      dockerfile: Dockerfile
    container_name: date-annotator
    networks:
      - nlp-sandbox-internal
    ports:
      - "80:8080"

networks:
  nlp-sandbox:
  nlp-sandbox-internal:
    internal: true