name: ci

on:
  push:
    branches:
      - main
      - develop
    release:
      types: [created]
  pull_request:

env:
  docker_repository: nlpsandbox/date-annotator-example

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Lint Dockerfiles
      uses: docker://hadolint/hadolint:latest
      with:
        entrypoint: hadolint
        args: src/server/Dockerfile

  test:
    needs: [lint]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox
        pip install tox
    # - name: Run integration tests
    #   run: |
    #     cd src/server
    #     tox

  build:
    needs: [test]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Dockerfile.base
      uses: docker/build-push-action@v1
      with:
        repository: ${{ env.docker_repository }}
        push: false

  # build-and-publish:
  #   needs: [test]
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set variables
  #     id: vars
  #     run: |
  #       if [[ ${GITHUB_REF} = refs/tags/* ]]
  #       then
  #         echo ::set-output name=version::${GITHUB_REF#refs/tags/}
  #         echo ::set-output name=push::true
  #       else
  #         echo ::set-output name=version::test
  #         echo ::set-output name=push::false
  #       fi

  #   - name: Build Dockerfile.base
  #     uses: docker/build-push-action@v1
  #     with:
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}
  #       repository: ${{ env.docker_repository }}
  #       tags: latest, ${{ steps.vars.outputs.version }}
  #       push: ${{ steps.vars.outputs.push }}